name: Simple Terraform Deploy

on:
  workflow_dispatch: # Allows manual trigger from the Actions tab

# Required for GitHub to request the OIDC token from AWS
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335391385:role/cicd-pipeline
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
